# Generated by Django 4.0 on 2023-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='hk_email',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
