# Generated by Django 4.0 on 2023-03-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0003_remove_customer_hk_email_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_name', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, max_length=50, null=True, upload_to='media/')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
