# Generated by Django 4.0 on 2023-03-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0004_views'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='views',
            new_name='v',
        ),
    ]
