# Generated by Django 4.0 on 2023-03-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0005_rename_views_v'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='v',
            new_name='View_more',
        ),
    ]
