# Generated by Django 4.0 on 2023-03-28 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0006_rename_v_view_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Creation_app.view_more')),
            ],
        ),
    ]
