# Generated by Django 4.0 on 2023-03-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0007_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='images',
            new_name='fk_img',
        ),
    ]
