# Generated by Django 4.0 on 2023-03-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Creation_app', '0008_rename_images_card_fk_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='card',
        ),
    ]
